spring:
  application:
    name: securityexam

#  security:
#    user:
#      name: carami
#      password: 1234

  datasource:
    url: jdbc:mysql://localhost:3306/securitydb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: spring
    password: spring1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: abcdefghijklmnopqrstuvwxzy123456
  access-expiration-ms: 1800000     #30 * 60 * 1000
  refresh-expiration-ms: 604800000  # 7Ïùº



server:
  tomcat:
    threads:
      max: 5
      min-spare: 3

logging:
  level:
    org:
      springframework:
        security: trace